### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by intlaqa** [danesparza/MailChimp.NET#129]
Hi, sometimes I get the following error message when subscribing:

"The request was aborted: Could not create SSL/TLS secure channel"

After restarting the application, it works for some hours then it fails returning the same message.

**Comment by yaronguez** [comment]
Hi we're getting the same error occasionally.  Any suggestions? We're filing a support ticket with MailChimp as well.

**Comment by yaronguez** [comment]
Hi we're still having this error on all calls to MailChimp.  MailChimp said nothing had changed on their end and that no other users were reporting it.  Furthermore the issue happens on both our server and local dev environment.  Any ideas are much appreciated, thanks!
