### ISSUE TITLE
Creating a IMailChimpManager interface

### ISSUE THREAD

**Issue by cntwo** [danesparza/MailChimp.NET#138]
Hi,

We're using this library, and it's serving us really well. The only downside is that it's not particularly helpful to being Mocked for testing. Would you be open to me submitting a PR adding interfaces for `MailChimpManager` and `MailChimpExportManager`?

Thanks for your hard work,
Alex

**Comment by danesparza** [comment]
@cntwo that sounds good.  It would be helpful if you also updated the README with a note about it, and gave some guidance to how you intended the Mocking to work.  (Nothing too fancy, just enough to get the idea.)  An example test in the testing project would probably be a good idea as well.  Thoughts?

**Comment by cntwo** [comment]
That sounds like a good plan. I'll put something together and get a PR submitted.

**Comment by cntwo** [comment]
Hi Dan,

It looks like there is no built in mocking framework. We use [Moq](https://github.com/Moq/moq4), however that would seem a little heavy to add as a dependency to the MailChimp.Tests project.

An example test wouldn't make much sense without the supporting framework, so I am more than happy to provide a more thorough example in the README.

What do you think?

Alex
