### ISSUE TITLE
Can we get async method implementations?

### ISSUE THREAD

**Issue by RPM1984** [danesparza/MailChimp.NET#140]
Pretty self-explanatory.

Doable?

**Comment by SteveVaneeckhout** [comment]
This library is targeted at .net 3.5 I think so async implementations are not going to be implemented in this version. Also, we should focus first on implementing the full Mailchimp API.

However, we can start thinking about a 2.0 version of this library where we upgrade the .NET requirement to 4.5 and implement a whole list of wishes users have made in the past.
@danesparza Could you enable the Wiki on this repo and create a 2.0 wishlist page?

**Comment by danesparza** [comment]
@SteveVaneeckhout Great idea!  Doing that now.  Feel free to add to it once I create it.

**Comment by danesparza** [comment]
I have turned on the wiki and added a page for a [vNext wishlist](https://github.com/danesparza/MailChimp.NET/wiki/MailChimp.NET-vNext-wishlist) (because hey -- we might as well use the Microsoft versioning convention, right?)
