### ISSUE TITLE
I have scenario what if MailChimp admin change intereste grouping name

### ISSUE THREAD

**Issue by gamien** [danesparza/MailChimp.NET#141]
Dear Sir,
I just try to prove of concept to work with MailChimp
I have the following scenario
If mailChimp Admin create interest group as flowed
Details:News Letter
and has 3 sub groups G1,G2,G3
If the admin join an account(X) to G1 my system can sync this but if the admin change group G1 to Group1 
how I can link the two subgroups to change in my database side?
currently I delete G1 and create another Group with Group1 and I lost the relation between the account(X) and Goup1(old name G1)

**Comment by danesparza** [comment]
I'm so sorry @gamien -- I'm not sure I understand your question.  Can you restate it in a different way?

**Comment by gamien** [comment]
I mean how I can sync inner interest groups(may called labels or subgroups) while the inner interest group without primary id to use as identifier.
Off course I can't use the name as identifier because admin can change it
