### ISSUE TITLE
Nuget packages is working only with serviceStack.Text = 3.9.71

### ISSUE THREAD

**Issue by dampee** [danesparza/MailChimp.NET#144]
This means we can't use other packages with a later version of serviceStack.

**Comment by danesparza** [comment]
Correct.  This is the last version of ServiceStack.Text with an open source license.  4.x introduced a different license scheme.  I'm open to other suggestions.

**Comment by danesparza** [comment]
See https://servicestack.net/download#free-quotas for more information

**Comment by dampee** [comment]
Didn't knew that. Sorry!  If ServiceStack.Text is only used for json serialization, move to newtonsoft ?

**Comment by dampee** [comment]
Or leave it up to the developer to upgrade, but keep the library on 3.9.x.
Currently I need to decide, start messing around with bindings or move to other mailchimp library.  I NEED another package which depends on servicestack (v4).

**Comment by dampee** [comment]
Would you consider a pull request with a change to NewtonSoft?

**Comment by SteveVaneeckhout** [comment]
Someone is already trying: https://github.com/jphellemons/MailChimp.NET

**Comment by SteveVaneeckhout** [comment]
I've added the Servicestack -> Newtonsoft request to the wishlist page on the wiki.

For the current version of Mailchimp.NET I think we should focus first on have a complete implementation of the Mailchimp API. Then we can start working on version 2 of this library.

**Comment by danesparza** [comment]
@dampee - You're welcome to clone and change over to NewtonSoft in your own repo.  I've tried to isolate much of the code required for that change in the `MakeAPICall` method.

@SteveVaneeckhout I agree with your sentiment of adding the item to the wishlist and trying to finish up the API client implementation.  

Thanks to both of you for getting involved!
