### ISSUE TITLE
Does MailChimp.NET wrapper supported in .NET 2.0

### ISSUE THREAD

**Issue by dskumar001** [danesparza/MailChimp.NET#145]
Hi,
The MailChimp.NET wrapper  is in .NET 3.5 some of the features are not supported in .NET 2.0.
Can you please help the changes to be made so that wrapper can work in .NET 2.0

**Comment by danesparza** [comment]
Sorry -- no.  You're welcome to fork the code, but the minimum .NET version we'll support is .NET 3.5 ([which came out in 2007](http://en.wikipedia.org/wiki/.NET_Framework_version_history#.NET_Framework_3.5)).
