### ISSUE TITLE
Unsubscribed by date range

### ISSUE THREAD

**Issue by teamofsteve** [danesparza/MailChimp.NET#147]
Hello. I'm using Mail Chimp and the API wrapper of the first time so this is probably very basic.
I can return a list of all members who have unsubscribed by using 
MembersResult results = mc.GetAllMembersForList(list.Id, "unsubscribed", 0, 100);

Can something similar be done by date range? I cannot see a param in this method or a similar method to do this. Can anyone advise please?

**Comment by utillity** [comment]
yes, use a segment to describe the date range: 


		private CampaignSegmentOptions CreateChangedSinceCriteria(DateTime? lastSync, DateTime maxDate)
		{
			var result = new CampaignSegmentOptions
			{
				Match = "all",
				Conditions = new List<CampaignSegmentCriteria>()
			};
			var crit = new CampaignSegmentCriteria
			{
				Field = "last_changed",
				Operator = "gt",
				Value = MailChimpManager.ConvertDateTimeToMailChimpAPI(lastSync.Value)
			};
			result.Conditions.Add(crit);
			{
				var crit = new CampaignSegmentCriteria
				{
					Field = "last_changed",
					Operator = "lt",
					Value = MailChimpManager.ConvertDateTimeToMailChimpAPI(maxDate)
				};
				result.Conditions.Add(crit);
			}
			return result;
		}
