### ISSUE TITLE
How do you use this behind a proxy?

### ISSUE THREAD

**Issue by hofo** [danesparza/MailChimp.NET#152]
Sorry if I've missed this somewhere, how do you use this behind a http proxy? I can see in the code we're using ServiceStack's PostJSONToURL as the HTTP interface, can I pass in arguments there that ServiceStack will use for the proxy?

**Comment by danesparza** [comment]
I think there is a way to set something in your `web.config` file.  Have you tried using the `<proxy>` element?  [Example here](https://msdn.microsoft.com/en-us/library/sa91de1e%28v=vs.110%29.aspx).  

You'd want to use this in the web.config or app.config of your calling app.
