### ISSUE TITLE
Strong name dll

### ISSUE THREAD

**Issue by EmanShaker** [danesparza/MailChimp.NET#154]
I was trying to reference the mailchimp.dll wrapper but my solution is signed, when I tried signing the wrapper it gave me error that "'ServiceStack.Text' does not have a strong name", any idea how to get a signed version?

**Comment by danesparza** [comment]
Great question.  

I haven't tried it, but this article talks about signing [3rd party assemblies](http://buffered.io/posts/net-fu-signing-an-unsigned-assembly-without-delay-signing/).   

Also, you might want to look at [this proposed solution on SO](http://stackoverflow.com/a/11408513/19020)

Incidentally, it's an open source project, and you can go back to the [v3 snapshot of the source](https://github.com/ServiceStack/ServiceStack.Text/releases/tag/v3-snapshot) to try signing the assembly yourself.

**Comment by EmanShaker** [comment]
Thanks a lot, I went with the last option to sign the source code.
