### ISSUE TITLE
Gettting users from list not working after first 100

### ISSUE THREAD

**Issue by kocakmstf** [danesparza/MailChimp.NET#159]
I'm using  GetAllMembersForList(listId, start: counter, limit: 100); method to take all my users from a list. First 100 result comes succesfully but after that data was empty. I have 6k user in my list. How can i take all of them. Here is my code block:

            var emailParameters=new List<EmailParameter>();
            int total = 100;
            int counter = 0;
            while (counter<=total)
            {
                MembersResult result = mailChimpManager.GetAllMembersForList(listId, start: counter , limit: 100);
               emailParameters.AddRange(result.Data.Select(c => new EmailParameter() { Email = c.Email }).ToList());
                total = result.Total;
                counter += 100;
            }

By the way if i say  
MembersResult result = mailChimpManager.GetAllMembersForList(listId, start: 200 , limit: 100); 
it also returns empty data array

**Comment by mikkoh85** [comment]
This is common problem. Use 1, 2, 3 in counter instead of 100, 200.. Etc. It means pages instead of row count

**Comment by matthewcanty** [comment]
Could you just change the parameter to save this happening?

How about `pageNumber`
