### ISSUE TITLE
nuget update-package fails because Unable to find a version of 'MailChimp.NET' that is compatible with 'ServiceStack.Text 4.0.40'.

### ISSUE THREAD

**Issue by jiripik** [danesparza/MailChimp.NET#160]
PM> update-package
No updates available for 'MailChimp.NET' in project 'EspApi.Vendors.MailChimp'.
No updates available for 'MailChimp.NET' in project 'EspApi.Vendors.MailChimp.Spikes'.
Updating 'ServiceStack.Text' from version '3.9.71' to '4.0.40' in project 'EspApi.Vendors.MailChimp'.
update-package : Updating 'ServiceStack.Text 3.9.71' to 'ServiceStack.Text 4.0.40' failed. Unable to find a version of 'MailChimp.NET' that is compatible with 'ServiceStack.Text 4.0.40'.
At line:1 char:1
+ update-package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
 
Updating 'ServiceStack.Text' from version '3.9.71' to '4.0.40' in project 'EspApi.Vendors.MailChimp.Spikes'.
update-package : Updating 'ServiceStack.Text 3.9.71' to 'ServiceStack.Text 4.0.40' failed. Unable to find a version of 'MailChimp.NET' that is compatible with 'ServiceStack.Text 4.0.40'.
At line:1 char:1
+ update-package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

**Comment by danesparza** [comment]
Please see issue #144
