### ISSUE TITLE
Create/Import List 

### ISSUE THREAD

**Issue by sendtoharmeet** [danesparza/MailChimp.NET#167]
I want to import my data for creating list through API call, I am able to create a campaign and run this campaign. Only if I have created user list at MailChimp.com.

I want to do fully automated system, so I can import my user list, create campaign and template, and can sent email to imported user.

**Comment by danesparza** [comment]
Is there something specific about the API wrapper I can help you with?  If you need help with the MailChimp API, I suggest you check out their [excellent help site](https://apidocs.mailchimp.com/).

**Comment by sendtoharmeet** [comment]
I am looking for any method which can create list on API. Is this code having any such method ?

Or MailChimp provides any API to create list ?

**Comment by balexandre** [comment]
@sendtoharmeet You need firstly, to understand, how MailChimp works and please read the rules carefully if you don't want them to block your account for high values of spam reports...

Soon you have mastered the flow in MailChimp website, all the calls are available in the API.

[MailChimp API](https://apidocs.mailchimp.com/) is available with all updated documentation, MailChimp.NET is only a wrapper for .NET that actually call those API methods, and each MailChimp API call is available in the wrapper.
