### ISSUE TITLE
GetListsForEmail returns an exception if the email address is not subscribed to any lists

### ISSUE THREAD

**Issue by williamsonjake** [danesparza/MailChimp.NET#173]
hey there,

this maybe a misunderstanding on my part so apologies if this isn't a bug...

i've some unsubscribe code that check's if the email address is in the list before attempting to unsubscribe them:

```
var emailParameter = new EmailParameter
{
	Email = email
};

var lists = _mailChimpManager.GetListsForEmail(emailParameter);

if (!lists.Any()) return;

var isInList = lists.FirstOrDefault(x => x.Id == listId);

if (isInList != null) _mailChimpManager.Unsubscribe(listId, emailParameter);
```
calling 'GetListsForEmail' with an address that doesn't have any lists returns an exception:

```
The email address "sophie.neale+14@gibedigital.com" is not subscribed to any lists.
```
am i going about this the wrong way? i guess in my head i was expecting an empty list to be returned rather than an exception...

whatcha reckon?!

cheers,

jake

**Comment by danesparza** [comment]
Great question, @williamsonjake ... 

So it looks like the `GetListsForEmail` method [calls](https://github.com/danesparza/MailChimp.NET/blob/b9c4f25799ba8ada91121d9658ac9b7f331e8538/MailChimp/MailChimpManager.cs#L2653) the MailChimp API endpoint [helper/lists-for-email](https://apidocs.mailchimp.com/api/2.0/helper/lists-for-email.php).  

Looking at their API docs, it looks like one of the errors this method could throw on the Mailchimp side is *List_NotSubscribed* -- so yes -- I think this is normal.

**Comment by williamsonjake** [comment]
hi,

i did a bit more digging on this one as i wasn't 100% happy with wrapping the above code in a try/catch to suppress the 'List_NotSubscribed' exception...

based on other suggestions i found, this is what i've run with:

```
public UnsubscribeResult UnSubscribe(string listId, string email)
{
	var emailParameter = new EmailParameter
	{
		Email = email
	};

	var memberInfo = _mailChimpManager.GetMemberInfo(listId, new List<EmailParameter> { emailParameter });

	var member = memberInfo.Data.FirstOrDefault();

	if (member == null) return new UnsubscribeResult { Complete = true };

	if (member.Status == "unsubscribed") return new UnsubscribeResult { Complete = true };

	return _mailChimpManager.Unsubscribe(listId, emailParameter);
}
```
the code works on the basis that the 'UnsubscribeResult' status is true if the member can't be found or can be found but is already unsubscribed from the list.

if the member is found in the list the 'UnsubscribeResult' status is set by the unsubscribe method response.

feels a bit cleaner and get's rid of the try/catch!

i suppose a 'nice to have' would be to add a status code to the 'UnsubscribeResult' class so you can return different outcome messages to the user rather than a simple true/false?

cheers,

jake
