### ISSUE TITLE
Create List

### ISSUE THREAD

**Issue by casper6060** [danesparza/MailChimp.NET#181]
Hi Danesparza, thanks for this awesome package! i would like to know if it possible to create a list ? would be nice if that could happen in the API so you dont have to go to MailChimp and do it each time

**Comment by danesparza** [comment]
Thanks for the feedback, @casper6060 -- much appreciated.  

Correct me if I'm wrong, but I don't see that as an operation supported on the [Mailchimp API]()https://apidocs.mailchimp.com/api/2.0/#lists-methods.  Sorry, I think you're out of luck.  Let me know if you find out different.

**Comment by SteveVaneeckhout** [comment]
@danesparza Mailchimp has added this function in version 3 of their api.

**Comment by danesparza** [comment]
@SteveVaneeckhout Thanks for the tip!

**Comment by ivebeenlinuxed** [comment]
Will this be added - can this at least be re-opened?
