### ISSUE TITLE
Obtaining All Members with GetAllMembersForList()

### ISSUE THREAD

**Issue by cgriser** [danesparza/MailChimp.NET#186]
I was wondering if there was a way to obtain all the members in a specified list. Instead of just obtaining 0 to 100.

Thanks for the help.

**Comment by danesparza** [comment]
The Mailchimp API indicates the [lists/members](https://apidocs.mailchimp.com/api/2.0/lists/members.php) method is paged automatically.  You can adjust the page size as high as 100.
