### ISSUE TITLE
.NET Wrapper for the MailChimp v3.0 API

### ISSUE THREAD

**Issue by Chintangandhi007** [danesparza/MailChimp.NET#195]
IS IT WORKING WITH NEW API VERSION BECAUSE MAILCHIMP HAS UPGRADED IT TO MailChimp v3.0 API and deprecated older version...

**Comment by mdissel** [comment]
Please use search before opening issues. This has been discussed a number of times..

**Comment by Chintangandhi007** [comment]
@mdissel  - Sorry that i have opened issue..  and What you suggest that i have go through all open and closed issue and then i have to open issue..

**Comment by mdissel** [comment]
a simple search on "3.0" returned three already closed issues.

**Comment by Chintangandhi007** [comment]
@mdissel - yes a simple search but is there a issue that i had opened the issue...
