### ISSUE TITLE
Subscribe don't work

### ISSUE THREAD

**Issue by hadisalehy** [danesparza/MailChimp.NET#204]
I want subscribe a member to exist list:
` 
var email = new EmailParameter
{
       Email = "hsa.hadi.zeos@gmail.com"
};
var results = mc.Subscribe(listId, email);
`
result value is:

- 		results:

- 		      Email	"hsa.hadi.zeos@gmail.com"	
- 		      EUId	"f995e137ac"	
- 		      LEId	"292171533"	

but new member don't add to exist list!
Why this method don't work?

**Comment by danesparza** [comment]
It sounds like you got an email Id and list Id back (and no error was returned) -- so I think you need to [contact Mailchimp support](https://mailchimp.com/contact/support/) for further help
