### ISSUE TITLE
Language field at AddSegment

### ISSUE THREAD

**Issue by AaronMorf** [danesparza/MailChimp.NET#206]
If I try to create a Segment where the field language should be a two letter iso code I get this error:
**"This list does not contain the Merge Field \"mc_language\""**

I tried it with "language" and also with "mc_language".

Or is there any other field name for the language?

**Comment by AaronMorf** [comment]
Somehow it is working now for me while using **"mc_language"**.
I don't know why it works now but it is good anyway.

**Comment by danesparza** [comment]
:smile: Glad to hear it @AaronMorf -- must have been an issue on the Mailchimp side?
