### ISSUE TITLE
Dependency of ServiceStack.Text v3.9.71

### ISSUE THREAD

**Issue by keesschollaart81** [danesparza/MailChimp.NET#44]
After updating the ServiceStack.Text library (via automatic NuGet updates) the MailChimp API throws a runtime TypeLoadException.

It occures since i updated to ServiceStack.Text v4.0.11 and says:

```
Could not load type 'ServiceStack.Text.WebRequestExtensions' from assembly 'ServiceStack.Text, Version=4.0.11.0, Culture=neutral, PublicKeyToken=null'.

[TypeLoadException: Could not load type 'ServiceStack.Text.WebRequestExtensions' from assembly 'ServiceStack.Text, Version=4.0.11.0, Culture=neutral, PublicKeyToken=null'.]
   MailChimp.MailChimpManager.MakeAPICall(String apiAction, Object args) +0
   .... (my namespaces)
```

As far as i figured out they removed this Exception type from this namespace. I think you should modify the nuget package depency of the MailChimp API package so that it does not allow the latest versions of ServiceStack.Text...? Or just update the MailChimp API so that it is compatible with the latest ServiceStack.Text updates!

**Comment by toriack** [comment]
When using Nuget to install Mailchimp it "forgets" to install the ServiceStack.Text dll. Just all it manually to your solution.
