### ISSUE TITLE
ServiceStack.Text version issue

### ISSUE THREAD

**Issue by rapPayne** [danesparza/MailChimp.NET#48]
Just got the latest NuGet package which installed ServiceStack.Text version 3.9.71.0 correctly.

When I run, though, I get this:

Foo : System.IO.FileNotFoundException : Could not load file or assembly 'ServiceStack.Text, Version=3.9.56.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

What needs to be done?  Anything I can do on my end?

**Comment by Calothis** [comment]
I'm seeing that error... Do I need a more recent version of the DLL?

Could not load file or assembly 'ServiceStack.Text, Version=3.9.71.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by danesparza** [comment]
@Calothis - are you also using a different version of ServiceStack.Text in your project?

**Comment by sitefinitysteve** [comment]
Our webapp has ServiceStack 4 installed, is there any way to assembly bind this up or something?  Could not load file or assembly 'ServiceStack.Text, Version=3.9.71.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by Calothis** [comment]
I don't know what any of this means...

Alex
