### ISSUE TITLE
using MergeVar to update FNAME, LNAME etc

### ISSUE THREAD

**Issue by SylviaJ** [danesparza/MailChimp.NET#5]
Can you give an example of how to use your MergeVar class to update FNAME etc...
I just can't see how it can be done at the moment. (of course i could be being blind!!!)
Thanks

**Comment by fly1967** [comment]
I'm having this issue as well. I'm using .Net 4.0. I changed the Target Framework to be 4.0 for MailChimp and the MailChimp.Tests projects. First name and last name aren't showing up in MailChimp. The subscriber is added to the list just fine. 

I altered SubscribeWithGroupSelection_Successful to make this call:
EmailParameter results = mc.Subscribe(strListID, email, mvso, "html" ,false, false, false, false);

The only thing I changed in the test was to pass in the other parameters to avoid the opt-in email. Do I have to download ServiceStack and recompile that too?

**Comment by mdissel** [comment]
Can you post a failing test?

**Comment by fly1967** [comment]
The test doesn't fail. It simply doesn't store first or last name in the
mailchimp site.

**Comment by mdissel** [comment]
Are you sure? (the fieldnames FNAME and LNAME are required in the first list in your account for a successful test)
I just re-run the test in my account and the fields are properly updated

**Comment by fly1967** [comment]
I'm sure. I went into my list definition on the site and marked these two
fields as REQUIRED and an error came back from the json call reporting
this, as expected.

I suspect that the service stack call is not parsing out the properties for
first and last name.

**Comment by comtsamsmith** [comment]
I wrote an article on a simple way up adding subscribers to a list using:
      Dim mailchimp As New ZmailChimp
      Dim ListId$ = "9b2e63f0b9"   'List Sage' List
      Dim email$ = "samsmith20@anymail.com" '"sam19@postcodelite.com"
      Dim fieldListOnAdd = "FNAME,Sam,LNAME,Smith,MTYPE,User,MID,631637"
      Dim fieldListOnUpdate = "FNAME,Sam,LNAME,Smith,MID,631637"  'Don't change MTYPE
      'Put on 'Sage One' and 'Sage 50' group
      Dim groupList = "407da9f47d,05086211ba"

      With mailchimp
         .API$ = "46cMailChimpAPIKeyd1de-us14" 'MailChimp API key
         .dataCenter$ = "us14"  'Last 4 letters of API key
         .password$ = "Password!"
         MsgBox(.addSubscriber(ListId$, email, fieldListOnAdd, fieldListOnUpdate, groupList))
      End With
      mailchimp = Nothing

see:http://www.codeproject.com/Tips/1140339/Mail-Chimp-Add-Update-e-mail-to-List-and-Subscribe	  
this may save someone some time
